### ISSUE TITLE
大佬能否关注一下latex渲染问题？谢谢

### ISSUE THREAD

**Issue by wzdnzd** [raedev/android-cnblogs#2]
- 首先，感谢大佬的付出，这是我见过的最好看的博客园app。很是期待12月底的新版本。

- 然后，能否关注一下之前在app里反馈过的latex渲染问题？强迫症表示每次都要点击“阅读原文”很难受😂

![wechatimg2](https://user-images.githubusercontent.com/8565764/49519917-1941be80-f8dd-11e8-85c7-3fb0927946c9.jpeg)

**Comment by raedev** [comment]
感谢支持哈！
您能否提供一下这篇文章的链接啊？

**Comment by wzdnzd** [comment]
https://www.cnblogs.com/pinard/p/9463815.html

**Comment by raedev** [comment]
v1.1.5 版本修复
