### ISSUE TITLE
新版无法登陆，旧版可以

### ISSUE THREAD

**Issue by aitiboy** [raedev/android-cnblogs#4]
机型：小米MIX 2
系统：MIUI10.2.2.0稳定版
版本：V2.01

![无法登陆_0](https://user-images.githubusercontent.com/7867975/55396909-99202280-5577-11e9-9d28-b2b77c5043fc.png)
![无法登陆_1](https://user-images.githubusercontent.com/7867975/55396910-99b8b900-5577-11e9-84a4-50dca5824dbc.png)

**Comment by raedev** [comment]
问题已经解决，请更新到最新版：[https://pgyer.com/cnblogs](点击下载)
