### ISSUE TITLE
网络请求这部分，使用Activity的Context，创建单例，确定不会造成内存泄漏么

### ISSUE THREAD

**Issue by KyneMaster** [raedev/android-cnblogs#7]
1、Activity中调用：IBlogApi blogApi = CnblogsApiFactory.getInstance(this).getBlogApi();

2、public static CnblogsApiProvider getInstance(Context context) {
        if (sProvider == null) {
            synchronized (CnblogsApiFactory.class) {
                if (sProvider == null) {
                    initProvider(context);
                }
            }
        }
        return sProvider;
    }

**Comment by raedev** [comment]
获取的是ApplicationContext不会造成泄漏
